### ISSUE TITLE
Update to scc 1.9.0

### ISSUE THREAD

**Issue by boyter** [pinpt/ripsrc#1]
Please update your dependency from 1.4.0 to 1.8.0. It will be considerably more accurate. You may need to set the following though `DisableCheckBinary = true` to disable the binary file check which should be the only backward incompatible change.

**Comment by boyter** [comment]
The next release 1.9.0 (sitting in master) will also be one to watch as well. It will be as accurate as tokei https://github.com/Aaronepower/tokei and should be faster than 1.8.0 to boot which is always a bonus.

**Comment by jhaynie** [comment]
@boyter do you know when you plan on releasing it yet?  /cc @josecordaz

**Comment by boyter** [comment]
Should be in a few more days. It should be 100% similar to 1.8.0 just with more accuracy and speed so in theory a straightforward upgrade from your end. The moment it is pushed out I will notify here.

**Comment by boyter** [comment]
1.9.0 pushed out. Much more accuracy for you and in addition you should see performance improvements across the board.
